Fikra/urls.py
from django.contrib import admin
from django.urls import path, include
from .settings import MEDIA_ROOT, MEDIA_URL, STATIC_ROOT, STATIC_URL
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls

admin.site.site_header  = "Fikra  managment"
admin.site.site_title  = "Fikra"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('cards/', include('cards.urls')),
    path('orders/', include('orders.urls')),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    path('', include('pwa.urls')),# إضافة مسارات PWA
] + debug_toolbar_urls()

urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from accounts.views import *

app_name = 'accounts'

urlpatterns = [
    path("", main_account_page, name="account_page"),
    path("account-info/", account_info, name="account_info"),
    path('mark-as-read/<int:message_id>/', mark_as_read, name='mark-as-read'),
    path("sign/", sign, name="sign"),
    path("verify-otp/", verify_otp, name="verify_otp"),
    path("choose-city/", choose_city, name="choose-city"),
    path('delete-account/', delete_account, name='delete_account'),
    path('edit-account/name/', edit_name, name='edit-name'),
    path('edit-account/password/', edit_account, name='edit-password'),
    path('edit-account/password/forget-password', forget_password, name='forget_password'),
    path('edit-account/password/enter-phone-number', phone_number_of_forgeted_password, name='phone_number_of_forgeted_password'),
    path('edit-account/password/verify-forget-password', verify_forget_password, name='verify_forget_password'),
    path('edit-account/password/reset-password', reset_password, name='reset_password'),
]

blog/urls.py
from django.urls import path
from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('', blog, name='blog'),
    path('blog-page/<slug:slug>/', page_details, name='page-details'),
    path('questions/', questions_page, name='questions-page'),
]

cards/urls.py
from django.urls import path
from cards.views import *

app_name = 'cards'

urlpatterns = [
    
    path('', cards_repo, name='cards-repo'),
    path('cards-store/', cards_store, name='cards-store'),
    path('copon-details/<cid>', copon_details, name='copon-details'),
    path('buy-copon/<cid>', buy_copon, name='buy-copon'),
    path('verfie-code/', verfie_code, name='verfie-code'),
        
]

orders/urls.py
from django.urls import path
from orders.views import *

app_name = 'orders'

urlpatterns = [
    path("", my_orders, name="my-orders"),
    path('admin/orders/<int:order_id>/print/', print_invoice_view, name='print_invoice'),
    path("order-details/<oid>", order_details, name="order-details"),
    path("create-order/", create_order, name="create-order"),
    path("edit-order/", edit_order, name="edit-order"),
    path("cancel-order/", cancel_order, name="cancel-order"),
    path("remove-order-item/", remove_order_item, name="remove-order-item"),
    path("dealing/<oid>", order_dealing, name="order-dealing"),
]

store/urls.py
from django.urls import path
from store.views import *

app_name = 'store'

urlpatterns = [
    path("", index, name="home"),
    
    path('serviceworker.js', service_worker, name='service_worker'),
    path('offline/', offline, name='offline'),
    path("brand/<slug:slug>/", brand_page, name="brand"),
    path("brands/all/", all_brands, name="all_brands"),
    path("category/<slug:slug>/", category_page, name="category"),
    path("categories/all/", all_categories_page, name="all_categories"),
    path("ad-details/<slug:slug>/", ads_page, name="ad_details"),
    path("offer/", offer_page, name="offer_page"),
    path("best-sales/", best_sales, name="best-sales"),
    path("search/", search_page, name="search_page"),
    path("favourite/", favourite_page, name="favourite_page"),
    path('add-to-favourites/<int:product_id>/', add_to_favourites, name='add_to_favourites'),
    path('favourite/clear/', clear_favourites, name='clear_favourites'),
    path("product/<pid>", product_details, name="product_details"),
    path('product/<int:pid>/interest/', add_interest, name='add_interest'),
    path('get-stock/', get_stock, name='get_stock'),  # مسار لجلب المخزون الخاص بالمنتج
    path('cart/', cart_page, name='cart_page'),
    path('add-to-cart/', add_to_cart, name='add_to_cart'),
    path('add-to-cart2/<str:pid>/', add_to_cart2, name='add_to_cart2'),
    path('remove-from-cart/<int:cart_item_id>/', remove_from_cart, name='remove_from_cart'),
    path('update-cart-item-qty/', update_cart_item_qty, name='update_cart_item_qty'),
    

]

templates/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ar">
    {% load pwa %} 
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content=" الوجهة المثالية لعشاق الأناقة، نقدم ملابس عصرية للرجال والنساء بتصاميم فريدة وجودة عالية، استمتعوا بتجربة تسوق ممتعة لتجديد إطلالتكم بأحدث صيحات الموضة.">
    <meta name="csrf-token" content="{{ csrf_token }}">
    <!-- import css files -->
    <link rel="stylesheet" href="{% static "/css/normalize.css" %}" media="print" onload="this.media='all'"> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/8.0.0/swiper-bundle.min.css" /> 
    <link rel="stylesheet" href="{% static "/css/all.min.css" %}">  <!-- Font Awesome Icons File     -->
    <link rel="stylesheet" href="{% static "/css/style.css" %}"> 
    {% comment %} ادراج ملفات css الخاصة بصفحة معينة هنا {% endcomment %}
    {% block additional_css %}{% endblock %}
    <!-- Preconnect to font servers for faster connection -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <!-- Preload font for faster rendering -->
    <link rel="preload" href="https://fonts.googleapis.com/css2?family=Almarai:wght@300;400;700;800&display=swap" as="style" onload="this.onload=null;this.rel='stylesheet'">
    <!-- Load the font stylesheet (fallback for browsers that don't support preload) -->
    <noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Almarai:wght@300;400;700;800&display=swap"></noscript>
    <!-- import PWA  -->
    <link rel="apple-touch-icon" href="{% static "/images/icons/small-logo.webp" %}" sizes="192x192">
    <link rel="manifest" href="{% static 'manifest.json' %}">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    {% progressive_web_app_meta %}
    <!-- website title & icon -->
    <title>Fikra</title>
    <link rel="website icon" type="" href="{% static "/images/icons/small-logo.webp" %}" sizes="192x192">

</head>
<body dir="rtl" class="" >

    <!-- لودر التحميل -->
    <div class="loader-container" id="loader">
        <div class="loader"></div>
    </div>

    {% comment %} لايوجد هيدر او ناف او فوتر بصفحة التسجيل والتحقق {% endcomment %}
    {% if request.path != '/accounts/sign/' and  request.path != '/accounts/verify-otp/' %} 
        {% include "partials/header.html" %}
    {% endif %}
    
    {% if request.path != '/accounts/sign/' and  request.path != '/accounts/verify-otp/' %}
        {% include "partials/nav.html" %}
    {% endif %}

    
    {% block content %}    
    {% endblock content %}
    
    {% include "pop-pages/added-to-cart.html" %}
    
    {% if request.path != '/accounts/sign/' and  request.path != '/accounts/verify-otp/' %}
        {% include "partials/footer.html" %}
    {% endif %}   

    
    <!-- import Javascript files -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/8.0.0/swiper-bundle.min.js" defer></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js" defer></script>
    <script src=" {% static "/javascript/pop-pages.js" %}" defer></script>
    <script src=" {% static "/javascript/main.js" %}"></script>

    {% comment %} ادراج ملفات js الخاصة بصفحة معينة هنا {% endcomment %}
    {% block additional_js %}{% endblock %}

</body>
</html>

templates/partials/footer.html
{% load static %}
<!-- Start Footer  -->
<div class="footer">
    <div class="links">
        <ul class="important-links"> 
            {% if men_category %}<li><a href=" {% url "store:category" men_category.slug %}" aria-label='التصنيفات الرجالية'><i class="fa-solid fa-angles-left"></i>المنتجات الرجالية</a></li>{% endif %}
            {% if women_category %}<li><a href=" {% url "store:category" women_category.slug %}" aria-label='التصنيفات النسائية'><i class="fa-solid fa-angles-left"></i>المنتجات النسائية</a></li>{% endif %}
            <li><a href="{% url "store:offer_page" %}"  aria-label="صفحة العروض"><i class="fa-solid fa-angles-left"></i>صفحة العروض</a></li>
            <li><a href="{% url "orders:my-orders" %}"  aria-label="صفحة الطلبات السابقة"><i class="fa-solid fa-angles-left"></i> طلباتي السابقة</a></li>
        </ul>
        <ul class="important-links">
            <li><a href="{% url "cards:cards-store" %}"  aria-label="متجر البطاقات"><i class="fa-solid fa-angles-left"></i>متجر البطاقات</a></li>
            <li><a href="{% url "cards:cards-repo" %}"  aria-label="مخزون البطاقات"><i class="fa-solid fa-angles-left"></i>مخزون بطاقاتي</a></li>
            <li><a href="{% url "blog:blog" %}"  aria-label="المدونة"><i class="fa-solid fa-angles-left"></i> المدونة</a></li>
            <li><a href="{% url "blog:questions-page" %}"  aria-label="الاسئلة الشائعة"><i class="fa-solid fa-angles-left"></i> الاسئلة الشائعة</a></li>
        </ul>
    </div>
    <div class="info">
        <h2>متجر فكرة </h2>
        <p> الوجهة المثالية لعشاق الأناقة، نقدم ملابس عصرية للرجال والنساء بتصاميم فريدة وجودة عالية، استمتعوا بتجربة تسوق ممتعة لتجديد إطلالتكم بأحدث صيحات الموضة.</p>
        <div class="contact-us">
            <h3>تواصل معنا </h3>
            <span>{{phone_number1}}</span>
            <span>{{phone_number2}} </span>
        </div>
        <div class="location">
            <h3> الموقع </h3>
            <p>ليبيا - طبرق</p>
        </div>
    </div>
    <div class="social">
        <div class="image"><img src="{% static "/images/admin-logo.webp" %}" alt="ايقونة الموقع"></div>    
        <ul class="social-icons">
            <li class="facebook"><a href="{{facebook_link}}" aria-label='تواصل على فيسبوك'><i class="fa-brands fa-facebook facebook"></i></a></li>
            <li class="tiktok"><a href="{{tiktok_link}}" aria-label='تواصل على انستغرام'><i class="fa-brands fa-tiktok tiktok"></i></a></li>
            <li class=" whatsapp"><a href="https://wa.me/{{whatsapp_link}}" aria-label='تواصل على واتساب'><i class="fa-brands fa-whatsapp whatsapp"></i></a></li>
        </ul>
    </div>
</div>
<div class="copy-rights">
<p> &copy; جميع الحقوق محفوظة لمتجر <span>فكرة</span></p>
<span>FIKRA</span>
</div>
<!-- End Footer  -->

templates/partials/header.html
{% load static %}
    <!-- Start Header  -->
    <header>
        <div class='header' id="header" >     
            <div class="upper-part">
                <div class="icons">
                    <!-- start mega-menu  -->
                    <input type="checkbox" name="" id="side-menu" hidden>
                    <label for="side-menu" class="menu"><i class="fa-solid fa-bars"></i></label> 
                    <div class="mega-menu">
                        <div class="top-icon">
                            <div class="exit">
                                <i class="fa-solid fa-xmark"></i>
                            </div>
                            <div class="toggle">
                                <input type="checkbox" name="" id="them">
                                <label for="them">
                                    <img src="{% static 'images/dark_mode_30dp_B18E4B_FILL0_wght400_GRAD0_opsz24.svg' %}" class="moon icon" alt="الوضع المظلم">
                                    <img src="{% static 'images/wb_sunny_30dp_B18E4B_FILL0_wght400_GRAD0_opsz24.svg' %}" class="sun icon" alt="الوضع الفاتح">
                                </label>    
                            </div>
                        </div>
                        <div class="links-sections">
                            <div class="title">
                                <h1>قسم الرجالي</h1>
                            </div>
                            <ul class="links">
                                {% for category in men_categories %}
                                    <li><a href="{% url 'store:category' category.slug %}" aria-label="اذهب الى {{ category.name }}"><i class="fa-solid fa-angles-left"></i> {{ category.name|slice:":-6"  }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="links-sections">
                            <div class="title">
                                <h1>قسم النسائي</h1>
                            </div>
                            <ul class="links">
                                {% for category in women_categories %}
                                    <li><a href="{% url 'store:category' category.slug %}" aria-label="اذهب الى {{ category.name }}"><i class="fa-solid fa-angles-left"></i> {{ category.name|slice:":-6"  }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="social-links">
                            <div class="title">
                                <h1>تواصل معنا</h1>
                            </div>
                            <ul class="links">
                                <li><a href="{{ facebook_link }}" aria-label="اذهب الى فيسبوك" ><i class="fa-brands fa-facebook"></i>فيسبوك</a></li>
                                <li><a href="{{ tiktok_link }}" aria-label="اذهب الى تيكتوك" ><i class="fa-brands fa-tiktok tiktok"></i>تيكتوك</a></li>
                                <li><a href="https://wa.me/{{whatsapp_link}}" aria-label="اذهب الى واتساب" ><i class="fa-brands fa-whatsapp"></i>واتساب</a></li>
                                <li><a href="mailto:{{ email }}?subject=استفسار&body=ارغب بالاستفسار عن  " aria-label="اذهب الى ايميل" ><i class="fa-regular fa-envelope"></i>ايميل</a></li>
                                <li><a href="tel:{{ phone_number1 }}" aria-label="تواصل معنا" ><i class="fa-solid fa-phone-volume"></i>اتصل بنا</a></li>
                            </ul>
                        </div>  
                        <div class="secondary-nav">
                            <ul>
                                <li class="li contact-us"><a href="https://wa.me/{{whatsapp_link}}" aria-label="اذهب الى واتساب" ><i class="fa-solid fa-headset"></i></a></li>
                                <li class="li"><a href="{% url "cards:cards-repo" %}" aria-label="مخزون البطاقات"><i class="fa-solid fa-gifts"></i></a></li>
                                <li class="li"><a href="{% url "orders:my-orders" %}" aria-label="طلباتي السابقة"><i class="fa-solid fa-list-check"></i></a></li>
                                <li class="li"><a href="{% url 'blog:blog' %}" aria-label="المدونة"><i class="fa-regular fa-circle-question"></i></a></li>
                            </ul>
                        </div>      
                    </div>  
                    <!-- end mega-menu  -->
                    <a href="{% url "accounts:account_info" %}#go_to_notfications" aria-label="الاشعارات" style="position: relative;">
                        <i class="fa-regular fa-bell bell"></i>
                        {% if unread_messages_count > 0 %}  <!-- اذا كان هنالك رسائل جديدة اظهر السبان والا اخفيه  -->
                            <span class="has-new-notif"></span>
                        {% endif %}
                    </a>
                </div>
                <div class="logo"  width='1200' height="1200">
                    <img src="{% static 'images/name-logo.webp' %}" alt="Fikra Store Name" >
                </div>
                <div class="points">
                    <a href="{% url "accounts:account_page" %}" aria-label="حسابي">
                        <span>{{ user_points }}</span>
                        <i class="fa-solid fa-gem"></i>                
                    </a>
                </div>
            </div>
            <div class="lower-part">
                <div class="categories">
                    <a class="category" href="{% url "store:all_brands" %}" aria-label="جميع البراندات">البراندات</a>
                    <a class="category" href="{% url "store:all_categories" %}" aria-label="جميع التصنيفات">التصنيفات</a>
                    <a class="category" href="{% url "store:offer_page" %}" aria-label="العروض">عروض</a>
                    {% if men_category %}<a class="category" href=" {% url "store:category" men_category.slug %}" aria-label="الملابس الرجالية"> رجالي</a>{% endif %}
                    {% if women_category %}<a class="category" href=" {% url "store:category" women_category.slug %}" aria-label="الملابس النسائية"> نسائي</a>{% endif %} 
                </div>
            </div>
        </div>
    </header>
    <!-- End Header  -->

templates/partials/nav.html
    <!-- Start Nav -->
    <nav>
        <div class="container">
            {% if request.path == '/cart/' %}
                <div class="go-confirm-order">
                    <div class="order">
                        <div class="price">
                            <span>السعر الإجمالي</span>
                            <span class='new-total-price'>{{ total_price|floatformat:0 }} دل</span>
                        </div>
                        <div class="show-receipt">
                            <input type="checkbox" name="" id="show" class="show">
                            <label for="show">عرض الفاتورة</label>
                        </div>
                    </div>
                </div>
            {% endif %}
            <div class="nav">
                <div class="nav-item {% if request.path == '/' %}active{% endif %}">
                    <a href=" {% url 'store:home' %}" aria-label="الرئيسية" id="home" ><i class="fa-solid fa-store"></i></a>
                    <label for="home">الرئيسية</label>
                </div>
                <div class="nav-item {% if request.path == '/cart/' %}active{% endif %}">
                    <a href="{% url 'store:cart_page' %}" aria-label="السلة" id="cart"><i class="fa-solid fa-bag-shopping"></i></a>
                    <label for="cart">السلة</label>
                </div>
                <div class="nav-item  {% if request.path == '/search/' %}active{% endif %}">
                    <a href="{% url 'store:search_page' %}" aria-label="البحث" id="search"><i class="fa-solid fa-magnifying-glass"></i></a>
                    <label for="search">البحث</label>
                </div>
                <div class="nav-item  {% if request.path == '/favourite/' %}active{% endif %}">
                    <a href="{% url 'store:favourite_page' %}" aria-label="المفضلة" id="fav"><i class="fa-solid fa-bookmark"></i></a>
                    <label for="fav">المفضلة</label>
                </div>
                <div class="nav-item  {% if request.path == '/accounts/' %}active{% endif %}">
                    <a href="{% url 'accounts:account_page' %}" aria-label="حسابي" id="account"><i class="fa-solid fa-circle-user"></i></a>
                    <label for="account">حسابي</label>
                </div>
            </div>
        </div>
    </nav>
    <!-- End Nav -->