Fikra/urls.py
from django.contrib import admin
from django.urls import path, include
from .settings import MEDIA_ROOT, MEDIA_URL, STATIC_ROOT, STATIC_URL
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls

admin.site.site_header  = "Fikra  managment"
admin.site.site_title  = "Fikra"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('cards/', include('cards.urls')),
    path('orders/', include('orders.urls')),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    path('', include('pwa.urls')),# إضافة مسارات PWA
] + debug_toolbar_urls()

urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from accounts.views import *

app_name = 'accounts'

urlpatterns = [
    path("", main_account_page, name="account_page"),
    path("account-info/", account_info, name="account_info"),
    path('mark-as-read/<int:message_id>/', mark_as_read, name='mark-as-read'),
    path("sign/", sign, name="sign"),
    path("verify-otp/", verify_otp, name="verify_otp"),
    path("choose-city/", choose_city, name="choose-city"),
    path('delete-account/', delete_account, name='delete_account'),
    path('edit-account/name/', edit_name, name='edit-name'),
    path('edit-account/password/', edit_account, name='edit-password'),
    path('edit-account/password/forget-password', forget_password, name='forget_password'),
    path('edit-account/password/enter-phone-number', phone_number_of_forgeted_password, name='phone_number_of_forgeted_password'),
    path('edit-account/password/verify-forget-password', verify_forget_password, name='verify_forget_password'),
    path('edit-account/password/reset-password', reset_password, name='reset_password'),
]

blog/urls.py
from django.urls import path
from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('', blog, name='blog'),
    path('blog-page/<slug:slug>/', page_details, name='page-details'),
    path('questions/', questions_page, name='questions-page'),
]

cards/urls.py
from django.urls import path
from cards.views import *

app_name = 'cards'

urlpatterns = [
    
    path('', cards_repo, name='cards-repo'),
    path('cards-store/', cards_store, name='cards-store'),
    path('copon-details/<cid>', copon_details, name='copon-details'),
    path('buy-copon/<cid>', buy_copon, name='buy-copon'),
    path('verfie-code/', verfie_code, name='verfie-code'),
        
]

orders/urls.py
from django.urls import path
from orders.views import *

app_name = 'orders'

urlpatterns = [
    path("", my_orders, name="my-orders"),
    path('admin/orders/<int:order_id>/print/', print_invoice_view, name='print_invoice'),
    path("order-details/<oid>", order_details, name="order-details"),
    path("create-order/", create_order, name="create-order"),
    path("edit-order/", edit_order, name="edit-order"),
    path("cancel-order/", cancel_order, name="cancel-order"),
    path("remove-order-item/", remove_order_item, name="remove-order-item"),
    path("dealing/<oid>", order_dealing, name="order-dealing"),
]

store/urls.py
from django.urls import path
from store.views import *

app_name = 'store'

urlpatterns = [
    path("", index, name="home"),
    
    path('serviceworker.js', service_worker, name='service_worker'),
    path('offline/', offline, name='offline'),
    path("brand/<slug:slug>/", brand_page, name="brand"),
    path("brands/all/", all_brands, name="all_brands"),
    path("category/<slug:slug>/", category_page, name="category"),
    path("categories/all/", all_categories_page, name="all_categories"),
    path("ad-details/<slug:slug>/", ads_page, name="ad_details"),
    path("offer/", offer_page, name="offer_page"),
    path("best-sales/", best_sales, name="best-sales"),
    path("search/", search_page, name="search_page"),
    path("favourite/", favourite_page, name="favourite_page"),
    path('add-to-favourites/<int:product_id>/', add_to_favourites, name='add_to_favourites'),
    path('favourite/clear/', clear_favourites, name='clear_favourites'),
    path("product/<pid>", product_details, name="product_details"),
    path('product/<int:pid>/interest/', add_interest, name='add_interest'),
    path('get-stock/', get_stock, name='get_stock'),  # مسار لجلب المخزون الخاص بالمنتج
    path('cart/', cart_page, name='cart_page'),
    path('add-to-cart/', add_to_cart, name='add_to_cart'),
    path('add-to-cart2/<str:pid>/', add_to_cart2, name='add_to_cart2'),
    path('remove-from-cart/<int:cart_item_id>/', remove_from_cart, name='remove_from_cart'),
    path('update-cart-item-qty/', update_cart_item_qty, name='update_cart_item_qty'),
    

]

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from accounts.models import User
from django.contrib.auth import authenticate
from django.core.exceptions import ValidationError
import phonenumbers

import logging
logger = logging.getLogger(__name__)  # تسجيل الأخطاء في اللوج

class UserSignUpForm(UserCreationForm):
    
    first_name = forms.CharField(widget=forms.TextInput(attrs={'id':"user-first-name"}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'id':"user-last-name"}))
    phone_number = forms.CharField(widget=forms.TextInput(attrs={'id':'user-phone'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'id':'passoword1'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'id':'passoword2'}))
    otp_code = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={'id': 'otp-code'}),
        help_text="سيتم إرسال رمز التحقق إلى رقم واتساب الخاص بك."
    )
    
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'phone_number', 'otp_code']
        
    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number')
        try:
            # التحقق من صحة رقم الهاتف حسب البلد 
            parsed_phone = phonenumbers.parse(phone_number, 'LY')
            if not phonenumbers.is_valid_number(parsed_phone):
                raise ValidationError("رقم الهاتف غير صالح.")
        except phonenumbers.NumberParseException:
            raise ValidationError("يرجى إدخال رقم هاتف صحيح.")
        except Exception as e:
            logger.error(f"خطأ داخل نموذج انشاء حساب: {e}", exc_info=True)
            raise ValidationError( 'حدث خطأ غير متوقع، الرجاء المحاولة لاحقًا')
        
        # التحقق مما إذا كان الرقم مسجلاً مسبقًا
        if User.objects.filter(phone_number=phone_number).exists():
            logger.warning(f"رقم الهاتف {phone_number} مستخدم بالفعل.")
            raise ValidationError("رقم الهاتف مستخدم بالفعل. يرجى تسجيل الدخول بدلاً من ذلك.")
        return phone_number
    
class UserLogInForm(forms.Form):
    phone_number = forms.CharField(max_length=15)
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        phone_number = self.cleaned_data.get('phone_number')
        password = self.cleaned_data.get('password')
        
        user = authenticate(phone_number=phone_number, password=password)
        if user is None:
            raise forms.ValidationError("رقم الهاتف أو كلمة المرور غير صحيحة.")
        return self.cleaned_data
    

accounts/views.py
from django.shortcuts import redirect, render, get_object_or_404
from accounts.forms import UserSignUpForm, UserLogInForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.hashers import check_password
from django.contrib import messages
from store.models import Product
from accounts.models import *
from accounts.utils import send_otp_via_whatsapp, format_phone_number
from django.core.exceptions import ValidationError
import phonenumbers
from django.core.cache import cache
from settings.models import Settings

import logging
logger = logging.getLogger(__name__)  # تسجيل الأخطاء في اللوج
security_logger = logging.getLogger('django.security') # إنشاء logger للأمان

# دالة صفحة الحساب الرئيسية
@login_required
def main_account_page(request):
    if request.method == 'POST' and 'logout' in request.POST: # التحقق من ضغط المستخدم على تسجيل الخروج
        logout(request)
        return redirect('store:home') # إعادة التوجيه بعد تسجيل الخروج
    best_sales_products = cache.get('best_sales_products')
    if not best_sales_products:
        best_sales_products = Product.objects.filter(ready_to_sale=True, total_sales__gt=0).select_related('category').prefetch_related('items__variations').order_by('-total_sales')[:8]
        cache.set('best_sales_products', best_sales_products, timeout=60*60)
        
    context = {'products' : best_sales_products ,} 
    return render(request, 'accounts/account.html', context)
# دالة تسجيل الدخول و انشاء الحساب
def sign(request):
    """
    اولا تتحقق هذه الدالة من ان المستخدم غير مسجل للدخول والا تحوله الى صفحة الحساب
    ثانيا التحقق من نوع الفورم الذي ارسله المستخدم ان كان تسجيل دخول او انشاء حساب
    """
    if request.user.is_authenticated:
        return redirect('accounts:account_page')
    
    # إعداد النماذج الافتراضية
    sign_up_form = UserSignUpForm
    login_form = UserLogInForm
    if request.method == 'POST':  
        
        form_type = request.POST.get('form-type')
                  
        if form_type == 'log':
            login_form = UserLogInForm(request.POST or None)
            if login_form.is_valid():
                phone_number = login_form.cleaned_data.get('phone_number')
                password = login_form.cleaned_data.get('password')
                
                user = authenticate(request, phone_number=phone_number, password=password)
                if user is not None:
                    # تسجيل الدخول الناجح
                    login(request, user)
                    return redirect('accounts:account_page')
                else:
                    # تسجيل محاولة تسجيل دخول فاشلة
                    security_logger.warning(f'محاولة تسجيل دخول فاشلة الى حساب: : {user}')
                    messages.error(request, "رقم الهاتف أو كلمة المرور غير صحيحة.")
        
        elif form_type == 'sign':
        
            sign_up_form = UserSignUpForm(request.POST or None)
            if sign_up_form.is_valid():
                phone_number = sign_up_form.cleaned_data['phone_number']
                first_name = sign_up_form.cleaned_data['first_name']
                last_name = sign_up_form.cleaned_data['last_name']
                otp_code = OTPVerification.generate_code()

                # تحقق ان المستخدم قام بتفعيل خدمة ارسال الرسائل
                send_otp = Settings.objects.values_list('send_otp_by_twilio', flat=True).first()
                if send_otp == False :
                    messages.error(request, "المعذرة خدمة انشاء حساب تم ايقافها مؤقتا من قبل مالك الموقع يرجى المحاولة لاحقا.")
                    return redirect('accounts:sign')
            
                # إرسال OTP عبر واتساب
                formatted_phone = format_phone_number(phone_number) 
                if formatted_phone:  
                    send_otp_via_whatsapp(formatted_phone, otp_code) 
                else:
                    messages.error(request, "يرجى إدخال رقم هاتف صالح.")  

                # تخزين OTP في قاعدة البيانات
                otp_instance = OTPVerification.objects.create(
                    phone_number=phone_number ,
                    code=otp_code
                )

                request.session['otp_id'] = otp_instance.id  # تخزين الـ OTP ID في الجلسة
                request.session['phone_number'] = phone_number  # تخزين رقم الهاتف
                request.session['first_name'] = first_name  
                request.session['last_name'] = last_name 
                return redirect("accounts:verify_otp")  # الانتقال لصفحة التحقق    
            
    context = {
        'sign_up_form': sign_up_form,
        'login_form': login_form,
    }     
        
    return render(request, 'accounts/sign.html', context)
# دالة التحقق من رقم الهاتف عند انشاء حساب
def verify_otp(request):
    # اذا كان المستخدم قد سجل دخوله بالفعل اعد توجيهه لصفحة الحساب الخاص به
    if request.user.is_authenticated:
        return redirect('accounts:account_page')
    
    if request.method == "POST":
        otp_code = request.POST.get("otp_code")
        otp_id = request.session.get("otp_id")
        phone_number = request.session.get("phone_number")
        first_name = request.session.get("first_name")
        last_name = request.session.get("last_name")
        if not otp_id:
            messages.error(request, "حدث خطأ، يرجى إعادة التسجيل.")
            return redirect("accounts:sign")

        otp_instance = OTPVerification.objects.filter(id=otp_id, phone_number=phone_number).first()

        if otp_instance :
            if  otp_instance.is_valid():
                if otp_instance.code == otp_code:
                    # إنشاء الحساب بعد التحقق
                    new_user = User.objects.create_user(phone_number=phone_number, first_name=first_name , last_name=last_name)
                    login(request, new_user)
                    otp_instance.delete()# حذف الكود من قاعدة البيانات
                    del request.session['otp_id']  # حذف الكود من الجلسة
                    messages.success(request, "تم التحقق بنجاح!")
                    return redirect("accounts:choose-city")
                else:
                    otp_instance.attempts += 1
                    otp_instance.save()
                    if otp_instance.attempts >= 3:
                        messages.error(request, "لقد تجاوزت الحد الأقصى للمحاولات.")
                        return redirect("accounts:sign")
                    else:
                        messages.error(request, "رمز التحقق غير صحيح، حاول مرة أخرى.")
            else: # حذف الكود ان كان منتهي الصلاحية او جرب ادخاله اكثر من 3 مرة
                otp_instance.delete()  # حذف الكود إذا لم يكن صالحًا
                del request.session['otp_id']  # حذف الـ OTP المخزن بالجلسة
                messages.error(request, "رمز التحقق انتهت صلاحيته. حاول من جديد.")
                return redirect("accounts:sign")
        else:
            messages.error(request, "المعذرة يبدو انه قد حصل خطأ اثناء توليد رمز التحقق الخاص بك , حاول مرة اخرى لاحقا")
            return redirect("accounts:sign")

    return render(request, "accounts/verify_otp.html")
# دالة عرض معلومات الحساب 
@login_required 
def account_info(request):
    user = request.user
    user_name = str(user.first_name + ' ' + user.last_name)
    phone_number = user.phone_number
    city = user.profile.city
    
    inbox = get_object_or_404(Inbox, user=user)
    messages = inbox.messages.all().order_by('is_read', '-timestamp')[:15]
    
    context  = {
        'user_name': user_name,
        'phone_number': phone_number,
        'city': city,
        'messages': messages,
    }
    return render(request, 'accounts/account-info.html', context)
# دالة تحديث حالة الرسالة
@require_POST
def mark_as_read(request, message_id):
    message = get_object_or_404(Message, id=message_id)
    message.is_read = True
    message.save()
    return JsonResponse({'status': 'success'})
# دالة حذف حساب
@login_required
def delete_account(request):
    if request.method == 'POST':
        user = request.user
        user.delete()  # حذف المستخدم
        logout(request)  # تسجيل خروج المستخدم بعد الحذف
    return redirect('store:home')  # إعادة توجيه إلى الصفحة الرئيسية
#  دالة تعديل كلمة المرور
@login_required
def edit_account(request):    
    if request.method == 'POST':
        # الحصول على البيانات من الفورم
        old_password = request.POST.get('old-password')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        # تحقق إن كان المستخدم  ادخل جميع البيانات المطلوبة 
        if old_password and password1 and password2 :
            if check_password(old_password, request.user.password):
                if password1 == password2:
                    if len(password1) >= 8 and ' ' not in password1 and not password1.isdigit() and password1.isascii():
                        request.user.set_password(password1)
                        update_session_auth_hash(request, request.user)  # الحفاظ على الجلسة
                        request.user.save()
                        messages.success(request, 'تم تحديث كلمة المرور بنجاح.')
                        return redirect('accounts:account_info')
                    else:
                        messages.error(request, 'كلمة المرور يجب أن تكون 8 أحرف على الأقل، ولا تحتوي على فراغات، ولا تكون عبارة عن أرقام فقط.')
                else:
                    messages.error(request, 'كلمتا المرور الجديدة غير متطابقتين.')
            else:
                messages.error(request, 'كلمة المرور القديمة غير صحيحة.')
        else:
            messages.error(request, 'يرجى إدخال البيانات المطلوبة.')

    return render(request, 'accounts/edit-password.html')
# ================================
#  دوال تعديل كلمة المرور المنسية
def forget_password(request):
    context = {}

templates/accounts/account-info.html
{% extends "partials/base.html" %}
{% load static %}

{% block additional_css %}
    <link rel="stylesheet" href="{% static "/css/accounts.css" %}">   
{% endblock %}

{% block content %}
    <div class="account-info-page" style="position: relative;">
        <!-- Start Ponits Section -->
        <div class="account-points">
            <a href="">
                <div class="container">
                    <div class="my-points">
                        <h3>نقاطي:</h3>
                        <div class="points">
                            <a href="">
                                <span>{{ user_points }}</span>
                                <i class="fa-solid fa-gem"></i>                
                            </a>
                        </div>
                    </div>
                 </div>
            </a>
        </div>
        <!-- End Ponits Section -->
        <!-- Start My Info Section  -->
        <div class="my-info">
            <div class="container">
                <div class="my-info-title">
                    <h2>بيانات حسابي</h2>
                    <button class="show-delete-menu"><i class="fa-regular fa-trash-can"></i></button>
                </div>
                <div class="my-info-details" id='go_to_notfications'>
                    <div class="details-item">
                        <div class="title"><p>اسم المستخدم</p><a href="{% url "accounts:edit-name" %}"><i class="fa-solid fa-pen"></i></a></div>
                        <div class="content">{{ user_name }}</div>
                    </div>
                    <div class="details-item">
                        <div class="title"><p>كلمة المرور</p><a href="{% url "accounts:edit-password" %}"><i class="fa-solid fa-pen"></i></a></div>
                        <div class="content">********</div>
                    </div>
                    <div class="details-item">
                        <div class="title"><p>رقم الهاتف</p></div>
                        <div class="content">{{ phone_number }}</div>
                    </div>
                    <div class="details-item">
                        <div class="title"><p>المدينة</p><a href="{% url "accounts:choose-city" %}"><i class="fa-solid fa-pen"></i></a></div>
                        <div class="content">{% if city %}{{ city }}{% else %}---{% endif %}</div>
                    </div>
                </div>
                <div class="notfication-section" id="notfications">
                    <h2>التنبيهات</h2>
                    {% if messages %}
                        {% for message in messages %}
                            <div class="notfication-message {% if message.is_read %}read{% endif %}">
                                <div class="title" onclick="toggleContent(this); markMessageAsRead('{% url 'accounts:mark-as-read' message.id %}', this);">
                                    <p> {{ message.subject }} </p>
                                    <span class="time"> {{ message.timestamp|date:"Y/m/d , h:i a "  }} </span>
                                    <i class="fa-solid fa-chevron-down"></i>
                                </div>
                                <p class="content"> {{ message.content|safe }} </p>
                            </div>    
                        {% endfor %}
                    {% endif %}
                </div>
            </div>    
            <!-- End My Info Section  -->
            <!-- Start delete-account Section -->
            <div class="Pop-up-page  delete-account">
                <div class="logo">
                    <img src="{% static "images/name-logo.webp" %}" alt="تخفيضات منتجات شي ان shein">
                </div>
                <p>هل انت متأكد انك تريد حذف حسابك بشكل نهائي؟</p>
                <div class="choices">
                    <button class="back" id="cancel-delete-btn">تراجع</button>
                    <button class="delete" id="confirm-delete-btn">حذف حسابي </button>
                </div>
                <script>
                    // هنا يمكنك تعيين رابط URL حذف الحساب
                    window.deleteAccountUrl = "{% url 'accounts:delete_account' %}";
                </script>
            </div>
            <!-- End delete-account Section -->
        </div>
    </div>
{% endblock content %}

templates/accounts/account.html
{% extends "partials/base.html" %}
{% load static %}

{% block additional_css %}
    <link rel="stylesheet" href="{% static "/css/accounts.css" %}">   
{% endblock %}

{% block content %}

    <div class="account-page" style="position: relative;">
        <!-- Start Ponits Section -->
        <div class="account-points">
            <a href="#">
                <div class="container">
                    <div class="my-points">
                        <h3>نقاطي:</h3>
                        <div class="points">
                            <a href="#">
                                <span>{{ user_points }}</span>
                                <i class="fa-solid fa-gem"></i>                
                            </a>
                        </div>
                    </div>
                 </div>
            </a>
        </div>
        <!-- End Ponits Section -->
        <!-- Start Account Menu Section  -->
        <div class="account-menu">
            <div class="container">
                <ul class="menu-items">
                    <li>
                        <a href="{% url "accounts:account_info" %}">
                            <div class="item">
                                <i class="fa-regular fa-user"></i>
                                <h5> بيانات حسابي </h5>
                            </div>
                            <i class="fa-solid fa-angles-left go-to"></i>
                        </a>
                    </li>
                    <li>
                        <a href="{% url "orders:my-orders" %}">
                            <div class="item">
                                <i class="fa-solid fa-list-check"></i>
                                <h5> طلباتي السابقة</h5>
                            </div>
                            <i class="fa-solid fa-angles-left go-to"></i>
                        </a>
                    </li>
                    <li>
                        <a href="{% url "cards:cards-repo" %}" id="share-icon">
                            <div class="item">
                                <i class="fa-solid fa-gifts"></i>
                                <h5>مخزون بطاقاتي</h5>
                            </div>
                            <i class="fa-solid fa-angles-left " ></i>
                        </a>
                    </li>
                    {% if request.user.is_staff %}
                        <li>                        
                            <a href="{% url 'admin:index' %}">
                                <div class="item">
                                    <i class="fa-solid fa-screwdriver-wrench"></i>
                                    <button>الذهاب الى صفحة الإدارة</button>
                                </div>
                                <i class="fa-solid fa-angles-left "></i>
                            </a>
                        </li>
                    {% else %}
                        <li>                        
                            <a class="download-fikra-link" id="install-link">
                                <div class="item">
                                    <i class="fa-solid fa-download"></i>
                                    <button id="pwa-download">تحميل فكرة على جهازي </button>
                                </div>
                                <i class="fa-solid fa-angles-left "></i>
                            </a>
                        </li>
                    {% endif %}
                    <li>
                        <a href="{% url "blog:blog" %}">
                            <div class="item">
                                <i class="fa-regular fa-circle-question"></i>
                                <h5>  المدونة </h5>
                            </div>
                            <i class="fa-solid fa-angles-left "></i>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <div class="item">
                                <i class="fa-solid fa-arrow-right-from-bracket"></i>
                                <h5>تسجيل الخروج </h5>
                            </div>
                            <i class="fa-solid fa-angles-left " ></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- End Account Menu Section  -->
        <!-- Start Sign-Out Section -->
        <div class="Pop-up-page sign-out">
            <div class="logo">
                <img src="{% static "images/name-logo.webp" %}" alt="">
            </div>
            <form method="POST" action="">
                {% csrf_token %}
                <p>هل انت متأكد انك تريد تسجيل الخروج من حسابك؟</p>
                <div class="choices">
                    <button type="button" class="back">تراجع</button>
                    <button type="submit" name="logout" class="out">تسجيل الخروج</button>
                </div>
            </form>
        </div>
        <!-- End Sign-Out Section -->
        <!-- Start download-fikra Section -->
        <div class="Pop-up-page download-fikra-page">
            <div class="logo">
                <img src="{% static "images/name-logo.webp" %}" alt="">
            </div>
            <p> لا يمكننا وصف سعادتنا لتحميلك تطبيقنا! من اعماق قلبنا شكراً لك</p>
        </div>
        <!-- End download-fikra Section -->
        <!-- Start Products Section -->
        <hr class="sep">
        <section  id="products">
            <a href="{% url 'store:best-sales' %}">
                <div class="title">
                    <h2>المنتجات الاعلى مبيعا</h2>
                    <i class="fa-solid fa-angles-left"></i>
                </div>
            </a>  
            <div class="swiper products-slider">
                <div class="swiper-wrapper">
                    {% for product in products %}
                        {% include "common/product-card.html" %}
                    {% endfor %}
                </div>
            </div> 
        </section>
        <!-- End Products Section -->
    </div>
      
      
    <script src=" {% static "/javascript/install-app.js" %}"></script>
{% endblock content %}
    

templates/accounts/edit-password.html
{% extends "partials/base.html" %}
{% load static %}
{% block additional_css %}
    <link rel="stylesheet" href="{% static "/css/accounts.css" %}">   
{% endblock %}
{% block content %}

<div class="sign-page" style="position: relative; padding-top:20px;">
    <div class="edit-card">
        <h1>تغيير كلمة المرور<i class="fa-solid fa-pen"></i></h1>

        <a class='edit-exit' href="javascript:void(0);" onclick="goBack()">
            <span class="exit-button"><i class="fa-solid fa-arrow-left"></i></span>
        </a>

        <form method='POST'>
            {% csrf_token %}
            <div class="data">
                {% if messages %}
                    {% for message in messages %}
                        {% if 'success' in message.tags %}
                            <div class="error-messages" style="background-color: #74a432 !important;">
                                {{ message }} 
                            </div>
                        {% else %}
                            <div class="error-messages">
                                {{ message }}
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                <div class="edit-items">                        
                    <div>
                        <label for="oldpassword">كلمة المرور القديمة <a href="{% url "accounts:forget_password" %}">هل نسيت كلمة المرور؟</a></label>
                        <input type="text" name="old-password" id="oldpassword" required>
                    </div>
                    <div>
                        <label for="password1">كلمة المرور الجديدة</label>
                        <input type="password" name="password1" id="password1" placeholder="(8 أحرف على الأقل)">
                    </div>
                    <div>
                        <label for="password2">تأكيد كلمة المرور</label>
                        <input type="password" name="password2" id="password2" placeholder="(ادخل كلمة المرور الجديدة للتأكيد)">
                    </div>
                    <button type="submit">تعديل</button>
                </div>
            </div>
            <div class="image">
                <img class="lazy-load" 
                    src="{% static 'images/square-default.webp' %}" 
                    data-src="{% static "images/graphic-designer.webp" %}"
                    alt="متجر فكرة طبرق"
                    width="168" height="168" 
                    loading="lazy"
                >
                <div class="shimmer-effect"></div>
            </div>

        </form>
    </div>           
</div>         
{% endblock content %}
{% block additional_js %}
{% endblock %}