Fikra/urls.py
from django.contrib import admin
from django.urls import path, include
from .settings import MEDIA_ROOT, MEDIA_URL, STATIC_ROOT, STATIC_URL
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls

admin.site.site_header  = "Fikra  managment"
admin.site.site_title  = "Fikra"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('cards/', include('cards.urls')),
    path('orders/', include('orders.urls')),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    path('', include('pwa.urls')),# إضافة مسارات PWA
] + debug_toolbar_urls()

urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from accounts.views import *

app_name = 'accounts'

urlpatterns = [
    path("", main_account_page, name="account_page"),
    path("account-info/", account_info, name="account_info"),
    path('mark-as-read/<int:message_id>/', mark_as_read, name='mark-as-read'),
    path("sign/", sign, name="sign"),
    path("verify-otp/", verify_otp, name="verify_otp"),
    path("choose-city/", choose_city, name="choose-city"),
    path('delete-account/', delete_account, name='delete_account'),
    path('edit-account/name/', edit_name, name='edit-name'),
    path('edit-account/password/', edit_account, name='edit-password'),
    path('edit-account/password/forget-password', forget_password, name='forget_password'),
    path('edit-account/password/enter-phone-number', phone_number_of_forgeted_password, name='phone_number_of_forgeted_password'),
    path('edit-account/password/verify-forget-password', verify_forget_password, name='verify_forget_password'),
    path('edit-account/password/reset-password', reset_password, name='reset_password'),
]

blog/urls.py
from django.urls import path
from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('', blog, name='blog'),
    path('blog-page/<slug:slug>/', page_details, name='page-details'),
    path('questions/', questions_page, name='questions-page'),
]

cards/urls.py
from django.urls import path
from cards.views import *

app_name = 'cards'

urlpatterns = [
    
    path('', cards_repo, name='cards-repo'),
    path('cards-store/', cards_store, name='cards-store'),
    path('copon-details/<cid>', copon_details, name='copon-details'),
    path('buy-copon/<cid>', buy_copon, name='buy-copon'),
    path('verfie-code/', verfie_code, name='verfie-code'),
        
]

store/urls.py
from django.urls import path
from store.views import *

app_name = 'store'

urlpatterns = [
    path("", index, name="home"),
    
    path('serviceworker.js', service_worker, name='service_worker'),
    path('offline/', offline, name='offline'),
    path("brand/<slug:slug>/", brand_page, name="brand"),
    path("brands/all/", all_brands, name="all_brands"),
    path("category/<slug:slug>/", category_page, name="category"),
    path("categories/all/", all_categories_page, name="all_categories"),
    path("ad-details/<slug:slug>/", ads_page, name="ad_details"),
    path("offer/", offer_page, name="offer_page"),
    path("best-sales/", best_sales, name="best-sales"),
    path("search/", search_page, name="search_page"),
    path("favourite/", favourite_page, name="favourite_page"),
    path('add-to-favourites/<int:product_id>/', add_to_favourites, name='add_to_favourites'),
    path('favourite/clear/', clear_favourites, name='clear_favourites'),
    path("product/<pid>", product_details, name="product_details"),
    path('product/<int:pid>/interest/', add_interest, name='add_interest'),
    path('get-stock/', get_stock, name='get_stock'),  # مسار لجلب المخزون الخاص بالمنتج
    path('cart/', cart_page, name='cart_page'),
    path('add-to-cart/', add_to_cart, name='add_to_cart'),
    path('add-to-cart2/<str:pid>/', add_to_cart2, name='add_to_cart2'),
    path('remove-from-cart/<int:cart_item_id>/', remove_from_cart, name='remove_from_cart'),
    path('update-cart-item-qty/', update_cart_item_qty, name='update_cart_item_qty'),
    

]

cards/models.py
from django.db import models
from django.utils.timezone import now  
from shortuuid.django_fields import ShortUUIDField
from store.models import Tag
from accounts.models import User
import string
from django.utils.html import mark_safe
from datetime import timedelta

class Copon(models.Model):
    code = ShortUUIDField(unique=True, length=12, max_length=20, alphabet= string.ascii_uppercase + string.digits , verbose_name='الكود')
    name = models.CharField(max_length=30 , verbose_name='الاسم')
    img = models.ImageField(upload_to='store/Cards/Copons', verbose_name='الصورة')
    value = models.PositiveIntegerField( verbose_name='القيمة')
    price = models.PositiveIntegerField(default=0, verbose_name='السعر')
    is_active = models.BooleanField(default=True, verbose_name='مفعل؟')
    expiration_days = models.IntegerField(default=365, verbose_name='يفسد بعد') # عدد الايام التي يفسد بعدها الكوبون
    sales_count = models.PositiveIntegerField(default=0, verbose_name='عدد المبيعات')  # عدد مرات بيع الكوبون
    tags = models.ManyToManyField(Tag,  blank=True, verbose_name='الهاشتاج')

    def __str__(self):
        return self.name
     
    def copon_image(self):
        # دالة مسؤولة عن عرض صورة المنتج المصغرة في لوحة الادارة
        return mark_safe("<img src='%s' width='50' height='50'/>" % (self.img.url) )
    
    class Meta:
        verbose_name = 'كوبون خصم'
        verbose_name_plural = 'كوبونات الخصم'
    
class CoponItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE , verbose_name='المشتري')  # المستخدم الذي اشترى الرمز
    copon_code = models.ForeignKey(Copon, on_delete=models.CASCADE, related_name='copon_usage' , verbose_name='الكوبون')  
    sell_price = models.IntegerField(default=0, verbose_name='سعر البيع بالنقاط') # سعر الكوبون عندما اشتراه المستخدم
    has_used = models.BooleanField(default=False, verbose_name='حالة الاستعمال')  # لتتبع إذا استخدم المستخدم الرمز
    purchase_date = models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الشراء')  # وقت شراء الرمز
    expire = models.DateField(null=True, blank=True, verbose_name='تاريخ انتهاء الصلاحية')
    receive_from_code = models.BooleanField(default=False, verbose_name='استلم من كود؟')
    def is_expire(self):
        if self.expire:
            if self.expire >= now().date():
                return False
            else:
                return True
        else:
            return False
    
    def use_copon(self):
        self.has_used = True
        self.expire = None
        self.save()
    
    def buy_copon(self):
        self.has_used = False # الكوبون غير مستخدم بعد الشراء
        self.expire = now().date() + timedelta(days=self.copon_code.expiration_days) # صلاحية جديدة عد اتمام الشراء
        self.sell_price = self.copon_code.price # سعر شراء الكوبون
        self.save()
    
    def __str__(self):
        return f"{self.user.first_name} - {self.copon_code.code}"
        
    class Meta:
        verbose_name = 'سجلات شراء الكوبونات'
        verbose_name_plural = 'سجلات شراء الكوبونات'

class ReceiveCopon(models.Model):
    copon = models.ForeignKey(Copon, on_delete=models.CASCADE, related_name='receive_copon', verbose_name='الكوبون')
    code = ShortUUIDField(unique=True, length=12, max_length=20, alphabet= string.ascii_uppercase + string.digits, verbose_name='الكود')  # كود فريد لهذا الكوبون المشتراة
    is_used = models.BooleanField(default=False, verbose_name='مستعمل؟')
    used_by = models.ForeignKey(User, null=True, on_delete=models.CASCADE, related_name='user' , verbose_name='استعمل بواسطة') # اذا كان مستخدما يتم انشاء علاقة مع المستخدم الذي اساخدمه
    note = models.TextField(null=True, blank=True, verbose_name='ملاحظة')
    created_at = models.DateField(auto_now_add=True, verbose_name='تاريخ الإنشاء')
    updated_at = models.DateField(auto_now=True, verbose_name='تاريخ التعديل')
        
    def __str__(self):
        return f'كود استلام ل{self.copon.name}'
        
    class Meta:
        verbose_name = 'كود استلام كوبون'
        verbose_name_plural = 'اكواد استلام كوبونات'
  

cards/views.py
from cards.models import *
from store.models import *
from accounts.models import UserProfile, Banned_users
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
import json
from accounts.send_messages import buy_copon_done_message, receive_copon_done_message
import logging
logger = logging.getLogger(__name__)  # تسجيل الأخطاء في اللوج

# ===================================================
# مستودع البطاقات
@login_required
def cards_repo(request):
    user = request.user
    today = now().date()
    user_copons = CoponItem.objects.filter(user=user, has_used=False).prefetch_related('copon_code')
    active_copons =  user_copons.filter(expire__gte=now().date()).order_by('-purchase_date')
    for copon in active_copons:
        if copon.expire and copon.expire >= today:
            copon.days_remaining = (copon.expire - today).days
        else:
            copon.days_remaining = 0  # الكوبون منتهي الصلاحية
    expired_copons  = user_copons.filter(expire__lt=now().date()).order_by('-purchase_date')[:5]
    copons_count = active_copons.count() + expired_copons.count()
    context  = {
        'active_copons': active_copons,
        'expired_copons': expired_copons,
        'copons_count': copons_count,
    }
    
    return render(request, 'cards/cards-repo.html',context)
# صفحة متجر البطاقات
def cards_store(request):    
    copons = Copon.objects.filter(is_active=True).only('name','value','img','price', 'expiration_days').order_by('value')
    context  = {
        'copons': copons,
    }
    return render(request, 'cards/cards-store.html',context)
# صفحة تفاصيل الكوبون
def copon_details(request, cid):
     
    copon = get_object_or_404(Copon, id=cid)
        
    context  = {
        'copon': copon,
    }
    return render(request, 'cards/copon-details.html', context)
# دالة شراء كوبون من اي مكان
@login_required
def buy_copon(request, cid):
    """
    دالة للتحقق من الكوبون المراد شرائه
    """
    if request.user.is_authenticated:
        user = request.user
    try:
        copon = get_object_or_404(Copon, id=cid)
        profile = get_object_or_404(UserProfile, user=user)
        inbox = profile.inbox
        points = profile.points
        
        # التحقق مما إذا كان المستخدم محظورًا عبر حسابه أو رقم هاتفه
        is_banned = Banned_users.objects.filter(user=user).exists() or \
                    Banned_users.objects.filter(phone_number=user.phone_number).exists()
        if is_banned:
            return JsonResponse({'error': 'لا يمكنك شراء الكوبون، حسابك أو رقم هاتفك محظور'}, status=403)
        
    except UserProfile.DoesNotExist:
        logger.error(f"ملف المستخدم غير موجود للمستخدم: {user}.", exc_info=True)
        return JsonResponse({'error': 'حدث خطأ أثناء الحصول على ملف المستخدم'}, status=500)
    except Copon.DoesNotExist:
        logger.error(f"الكوبون غير موجود: {cid}.", exc_info=True)
        return JsonResponse({'error': 'الكوبون غير موجود'}, status=404)
    except Exception as e:
        logger.error(f"خطأ غير متوقع: {e}", exc_info=True)
        return JsonResponse({'error': 'حدث خطأ غير متوقع، الرجاء المحاولة لاحقًا'}, status=500)
    
    # التحقق من أن المستخدم لديه نقاط كافية
    if copon.price > points:
        logger.warning(f"المستخدم {user} حاول شراء كوبون {cid} بدون نقاط كافية.")
        return JsonResponse({'error': 'لاتوجد نقاط كافية لإتمام عملية الشراء'}, status=400)
       
    user_copon = CoponItem.objects.create(
        user=user,
        copon_code=copon,    
    )
        
    # ارسال رسالة عند شراء كوبون
    message = buy_copon_done_message(user_name=user_copon.user.first_name, copon_name=user_copon.copon_code)
    inbox.add_message(message)
    
    # خصم النقاط وحفظ التحديثات
    points -= copon.price
    profile.points = points
    # لو نقاط المستخدم صارت سالب معناها قدر يتجاوز التحقق السابق بشكل ما واشترى الكوبون بدون ما يدفع
    if profile.points < 0 :
        logger.warning(f"نقاط المشتري {user} اصبحت سالبة بعد شرائه للكوبون {copon}")
    profile.save()
    
    # حفظ سجل استخدام الكوبون
    copon.sales_count += 1 
    user_copon.buy_copon()
    copon.save()
    user_copon.save()

    return JsonResponse({'success': 'تم شراء الكوبون بنجاح'}, status=200)
# دالة استلام هدية من الكود 
@login_required
def verfie_code(request):
    user = request.user

    if request.method == 'POST':        
        
        data = json.loads(request.body)
        verfie_code = data.get('verfie-code')
    
        try:
            verfie_copon = ReceiveCopon.objects.get(code=verfie_code)

            if verfie_copon.is_used:
                logger.info(f"User {user} tried to use an already used code: {verfie_code}")
                return JsonResponse({"success": False, "message": "الكود الذي ادخلته مستخدم بالفعل"})

            # إنشاء CoponItem جديد
            copon_item = CoponItem.objects.create(
                user=user,
                copon_code=verfie_copon.copon,   
                receive_from_code=True, 
            )

            verfie_copon.copon.sales_count += 1 
            copon_item.buy_copon()
            copon_item.sell_price = 0 # عند الحصول على الكوبون من كود فإن سعر شراءه صفر 
            verfie_copon.copon.save()
            copon_item.save()
            
            # تحديث حالة الكود إلى "مستخدم"
            verfie_copon.is_used = True
            verfie_copon.used_by = user
            verfie_copon.save()
            
            # ارسال رسالة عند اتمام استلام الكوبون
            message = receive_copon_done_message(user_name=request.user.first_name, copon_name=verfie_copon.copon)
            request.user.inbox.add_message(message)
            logger.info(f"User {user.username} successfully received the coupon: {verfie_copon.copon.name}")
            return JsonResponse({"success": True, "message": 'تهانينا! تم استلام الكوبون بنجاح.'})

        except ReceiveCopon.DoesNotExist:
            logger.warning(f"المستخدم {user}يحاول ادخال كود استلام كوبون غير موجود وهو:{verfie_code}")
            return JsonResponse({"success": False, "message": "الكود غير صحيح."})
        except Exception as e:
            logger.error(f"خطأ بدالة استرداد كوبون من الرمز الخاص به: {e}", exc_info=True)
            return JsonResponse({'success': False, 'error': 'حدث خطأ غير متوقع، الرجاء المحاولة لاحقًا'})

    logger.warning(f"المستخدم {user} وصل الى دالة verfie_code بطريقة خاطئة.")
    return JsonResponse({"success": False, "message": "طريقة وصول خاطئة"})

# ===================================================

templates/common/added-to-cart.html
{% load static %}

<!-- Start add-cart-pop-page Section -->
 <div class="Pop-up-page add-cart-pop-page">
    <div class="logo">
        <img src="{% static "/images/name logo.jpg" %}" alt="فكرة أناقة ">
    </div>
    <p>تمت الإضافة إلى السلة بنجاح</p>
    <i class="fa-solid fa-circle-check"></i>
</div>
<!-- End add-cart-pop-page Section -->

templates/common/card.html
{% load static %}

<div class="specific">
    <div class="product-box ">
        <a href=" {% url "cards:copon-details" card.id %}">
            <div class="product-image">
                <img class="lazy-load" 
                        src="{% static 'images/square-default.webp' %}" 
                        data-src="{{ card.img.url }}" 
                        alt="{{ card.name }} تخفيض"
                        loading="lazy" 
                        height="168" width="210"
                >
                <div class="shimmer-effect"></div>
            </div>
            <div class="product-info">
                <h4 class="product-name">{{ card.name }}</h4>

                <p class="product-description">القيمة: {{ card.value }}دينار </p>

                <h4 class="product-price point">

                    <div class="buy-by-points {% if  card.price > user_points %}forbidden{% endif %}{% if card.price == 0 %}free{% endif %} ">
                        {% if card.price == 0 %} 
                            مجانا 
                        {% else %}
                            {{ card.price }}<i class="fa-solid fa-gem"></i>
                        {% endif %} 
                    </div>   

                </h4>
            </div>
        </a> 
        {% if user.is_authenticated  %}
            {% if user_points >= card.price  %}
                <span class="add-to-cart">
                    <a href="{% url "cards:buy-copon" card.id %}" class="copon-buy-done-link">
                        <span> شراء </span><i class="fa-solid fa-cart-shopping"></i>
                    </a>
                </span>
            {% else %}
                <span class="add-to-cart disabled ">
                    <a href="#" class=""><span > شراء </span><i class="fa-solid fa-cart-shopping"></i></a>
                </span>
            {% endif %}
        {% else %}
            <span class="add-to-cart">
                <a href="{% url 'accounts:sign' %}" ><span>سجل أولا!</span></a>
            </span>
        {% endif %}
    </div>
</div>
<script>
    {% comment %} دالة تمنع النقر المتتالي على زر الشراء {% endcomment %}
    document.addEventListener("DOMContentLoaded", function () {
        function disableClickTemporarily(link, delay = 2000) {
            if (link.classList.contains("disabled")) return; // منع النقر المتكرر أثناء التعطيل
            link.classList.add("disabled");
            link.style.pointerEvents = "none"; // تعطيل النقر
            link.style.opacity = "0.5"; // تقليل الشفافية أثناء التعطيل

            setTimeout(() => {
                link.classList.remove("disabled");
                link.style.pointerEvents = "auto"; // إعادة تفعيل النقر
                link.style.opacity = ""; // إعادة الرابط لوضعه الطبيعي
            }, delay);
        }
        // استهداف جميع الروابط التي تحتوي على الكلاس "copon-buy-done-link"
        const links = document.querySelectorAll(".copon-buy-done-link");
        links.forEach(link => {
            link.addEventListener("click", function (event) {
                disableClickTemporarily(this);
            });
        });
    });    
</script>

templates/common/copon-repo-card.html
{% load static %}


<!-- product-start -->
<div class="specific">
    <div class="product-box offer ">
        <a {% if usage_copon.is_expire %} style='opacity:0.5;' {% endif %}>
            <div class="product-image">
                <div class="off-holder" >
                    {% if usage_copon.is_expire %}
                        <span>منتهية</span>
                    {% endif %}
                </div>
                <img class="lazy-load" 
                        src="{% static 'images/square-default.webp' %}" 
                        data-src="{{ usage_copon.copon_code.img.url }}" 
                        alt="خصم {{ usage_copon.copon_code.name }}"
                        loading="lazy" 
                        height="168" width="210"
                >
                <div class="shimmer-effect"></div>
            </div>
            <div class="product-info">
                <h4 class="product-name">{{ usage_copon.copon_code.name }}</h4>
                <p class="product-description card-info">القيمة: {{ usage_copon.copon_code.value }}دينار <br>
                    {% if usage_copon.is_expire %} 
                        انتهت صلاحيتها بتاريخ {{ usage_copon.expire }}
                    {% else %}
                        الصلاحية: {{ usage_copon.expire }} <br>
                        متبقي {{ usage_copon.days_remaining}} يوم
                    {% endif %}
                </p>
            </div>
        </a> 
        <span class="add-to-cart" style='opacity:1.0;'>
            {% if usage_copon.is_expire %}
                <a href="{% url "cards:buy-copon"  usage_copon.copon_code.id %}" class="copon-buy-done-link">
                    <span> اعد الشراء</span><i class="fa-solid fa-cart-shopping"></i>
                </a>
            {% else %}
                    {% comment %} رابط لصفحة الاسئلة  ان كان المستخدم مالك البطاقة{% endcomment %}
                    <a href="{% url "blog:questions-page" %}#how-to-use-copon"><span><i class="fa-solid fa-lightbulb" style="padding:0 2px;text-align:center;"></i></span></a>
            {% endif %}
            
        </span>
    </div>
</div>
<!-- product-end -->

templates/common/no-result.html
<div class="no-result">
    <h2>نعتذر لايوجد نتائج لعرضها حالياً</h2>
    <i class="fa-solid fa-face-frown"></i>
</div>

templates/common/product-card.html
{% load static %}
{% load filters %}

<!-- product-start -->
<div class="swiper-slide product-box {% if product.offer %} offer {% endif %}"> <!-- اضف كلاس اوفر اذا كان هنالك تخفيض- -->
    <a href="{% url "store:product_details" product.id %}" aria-label="استعرض {{product.name}}">
        <div class="product-image">
            <div class="off-holder">
                {% if product.get_total_stock > 0 %}
                    <span>{{product.get_offer_percentage|floatformat:0}}% </span>
                {% endif %}
            </div>
            <img class="lazy-load" 
                    src="{% static 'images/square-default.webp' %}" 
                    data-src="{{ product.thumbnail_img.url }}" 
                    alt="{{ product.name}}" 
                    loading="lazy" 
                    height="168" width="210"
            >
            <div class="shimmer-effect"></div>
        </div>
        <div class="product-info">
            <div class="product-name"> {{ product.name|slice:":20" }}{% if product.name|length > 20 %}...{% endif %}</div> <!-- اقصى طول 20 حرف -->
                <p class="product-description">  {{ product.description|striptags|html_unescape|slice:50 }}{% if product.description|striptags|length > 50 %}...{% endif %}</p> <!-- اقل طول 42 حرف اقصى طول 50 حرف -->

            {% if product.available %}
                <div class="product-price">
                    <div class="buy-by-money"><span class="old"> {{ product.price }} </span><span class="new"> | {{ product.new_price |floatformat:0 }} </span><span> دل </span></div>
                </div>
            {% else %}
                <div class="product-price" style='color:#9D2121;text-wrap:nowrap;'>
                    نفذت الكمية 
                </div>
            {% endif %}


        </div>
    </a> 

    {% comment %} الكود الخاص  بزر اضافة الى المفضلة {% endcomment %}
    {% if user.is_authenticated %}
        <span class="add-to-fav">
                <a href="{% url 'store:add_to_favourites' product.id %}" aria-label="اذهب الى المفضلة" class="add-to-fav-link" data-product-id="{{ product.id }}">
                    {% if request.path == '/favourite/' %}
                            <i class="fa-regular fa-trash-can"></i>
                    {% else %}
                        {% if product.id in favourite_products %}
                            <i class="fa-solid fa-heart"></i>
                        {% else %}
                            <i class="fa-regular fa-heart"></i>
                        {% endif %}
                    {% endif %}
                </a>
        </span>
    {% else %}
        <span class="add-to-fav">
            <a href="{% url 'accounts:sign' %}" class="add-to-fav-link" aria-label="تسجيل الدخول لحسابك">
                    <i class="fa-regular fa-heart"></i>
            </a>
        </span>
    {% endif %}

    {% comment %} الكود الخاص  بزر اضافة الى السلة {% endcomment %}
    {% if user.is_authenticated %}
        {% if product.get_total_stock > 0 %}

            <span class="add-to-cart">
                <a href="{% url 'store:add_to_cart2' product.pid %}" class="add-to-cart-link" aria-label="اضف الى السلة">
                    <span> إضافة الى السلة </span><i class="fa-solid fa-cart-shopping"></i> 
                </a>
            </span>

        {% endif %}
    {% endif %}


</div>
<!-- product-end -->