Fikra/urls.py
from django.contrib import admin
from django.urls import path, include
from .settings import MEDIA_ROOT, MEDIA_URL, STATIC_ROOT, STATIC_URL
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls

admin.site.site_header  = "Fikra  managment"
admin.site.site_title  = "Fikra"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('cards/', include('cards.urls')),
    path('orders/', include('orders.urls')),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    path('', include('pwa.urls')),# إضافة مسارات PWA
] + debug_toolbar_urls()

urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from accounts.views import *

app_name = 'accounts'

urlpatterns = [
    path("", main_account_page, name="account_page"),
    path("account-info/", account_info, name="account_info"),
    path('mark-as-read/<int:message_id>/', mark_as_read, name='mark-as-read'),
    path("sign/", sign, name="sign"),
    path("verify-otp/", verify_otp, name="verify_otp"),
    path("choose-city/", choose_city, name="choose-city"),
    path('delete-account/', delete_account, name='delete_account'),
    path('edit-account/name/', edit_name, name='edit-name'),
    path('edit-account/password/', edit_account, name='edit-password'),
    path('edit-account/password/forget-password', forget_password, name='forget_password'),
    path('edit-account/password/enter-phone-number', phone_number_of_forgeted_password, name='phone_number_of_forgeted_password'),
    path('edit-account/password/verify-forget-password', verify_forget_password, name='verify_forget_password'),
    path('edit-account/password/reset-password', reset_password, name='reset_password'),
]

blog/urls.py
from django.urls import path
from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('', blog, name='blog'),
    path('blog-page/<slug:slug>/', page_details, name='page-details'),
    path('questions/', questions_page, name='questions-page'),
]

cards/urls.py
from django.urls import path
from cards.views import *

app_name = 'cards'

urlpatterns = [
    
    path('', cards_repo, name='cards-repo'),
    path('cards-store/', cards_store, name='cards-store'),
    path('copon-details/<cid>', copon_details, name='copon-details'),
    path('buy-copon/<cid>', buy_copon, name='buy-copon'),
    path('verfie-code/', verfie_code, name='verfie-code'),
        
]

store/urls.py
from django.urls import path
from store.views import *

app_name = 'store'

urlpatterns = [
    path("", index, name="home"),
    
    path('serviceworker.js', service_worker, name='service_worker'),
    path('offline/', offline, name='offline'),
    path("brand/<slug:slug>/", brand_page, name="brand"),
    path("brands/all/", all_brands, name="all_brands"),
    path("category/<slug:slug>/", category_page, name="category"),
    path("categories/all/", all_categories_page, name="all_categories"),
    path("ad-details/<slug:slug>/", ads_page, name="ad_details"),
    path("offer/", offer_page, name="offer_page"),
    path("best-sales/", best_sales, name="best-sales"),
    path("search/", search_page, name="search_page"),
    path("favourite/", favourite_page, name="favourite_page"),
    path('add-to-favourites/<int:product_id>/', add_to_favourites, name='add_to_favourites'),
    path('favourite/clear/', clear_favourites, name='clear_favourites'),
    path("product/<pid>", product_details, name="product_details"),
    path('product/<int:pid>/interest/', add_interest, name='add_interest'),
    path('get-stock/', get_stock, name='get_stock'),  # مسار لجلب المخزون الخاص بالمنتج
    path('cart/', cart_page, name='cart_page'),
    path('add-to-cart/', add_to_cart, name='add_to_cart'),
    path('add-to-cart2/<str:pid>/', add_to_cart2, name='add_to_cart2'),
    path('remove-from-cart/<int:cart_item_id>/', remove_from_cart, name='remove_from_cart'),
    path('update-cart-item-qty/', update_cart_item_qty, name='update_cart_item_qty'),
    

]

store/views.py
from store.models import *
from cards.models import  CoponItem
from settings.models import Settings
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import Q, Count
from django.http import JsonResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils.timezone import now 
from django.views.decorators.csrf import csrf_protect
from django.core.cache import cache
from django.http import HttpResponse
import os
from django.conf import settings
import logging
logger = logging.getLogger(__name__)  # تسجيل الأخطاء في اللوج

def service_worker(request):
    service_worker_path = os.path.join(settings.BASE_DIR, 'serviceworker.js')
    try:
        with open(service_worker_path, encoding='utf-8') as serviceworker_file:
            return HttpResponse(serviceworker_file.read(), content_type='application/javascript')
    except FileNotFoundError:
        return HttpResponse('Service worker file not found', status=404)
# ===================================================
# صفحة الاوف لاين
def offline(request):
    return render(request, 'store/offline.html')
# ===================================================
# الصفحة الرئيسية
def index(request):
    # جلب الإعلانات التي يتم عرضها
    ads = AdsSlider.objects.filter(show=True)
    # جلب العلامات التجارية من الكاش أو قاعدة البيانات
    brands = cache.get('brands')
    if not brands:
        brands = Brand.objects.filter(featured=True)
        cache.set('brands', brands, 60*15)
    #جلب اسم المستخدم الاول اذا كان مسجل دخول 
    user_name = request.user.first_name if request.user.is_authenticated else None
    # جلب الفئات المميزة والظاهرة فقط، وتحميل المنتجات التابعة لهذه الفئات
    categories = Category.objects.filter(
        featured=True,
        status='visible',
        gender_cat=False,
    ).prefetch_related(
        'products', 'products__items__variations'
    ).filter(
        products__featured=True,
        products__ready_to_sale=True,
    ).distinct()[:8]
    offered_products = Product.objects.filter(ready_to_sale=True, offer=True).select_related('category').prefetch_related('items__variations')[:8] # تحميل العناصر ومتغيراتها دفعة واحدة
    best_sales_products = cache.get('best_sales_products')
    if not best_sales_products:
        best_sales_products = Product.objects.filter(ready_to_sale=True, total_sales__gt=0).select_related('category').prefetch_related('items__variations').order_by('-total_sales')[:8]
        cache.set('best_sales_products', best_sales_products, timeout=60*60)
    context = {
        'ads': ads,
        'brands': brands,
        'user_name': user_name,
        'categories': categories,
        'offered_products':offered_products,
        'best_sales_products':best_sales_products,
    }
    return render(request, 'store/index.html', context)
# ===================================================
# صفحة الاعلان
def ads_page(request, slug):
    ad = get_object_or_404(AdsSlider, slug=slug)
    ad_content = AdsProducts.objects.filter(Ads_name=ad).prefetch_related('product', 'product__items__variations')
    
    context = {
        'ad_content': ad_content,
        'ad': ad,
    }
    return render(request, 'store/ads-details.html', context)
# ===================================================
# صفحة العلامة التجارية
def brand_page(request, slug):
    brand = get_object_or_404(Brand, title=slug)
    last_products = Product.objects.filter(brand=brand, ready_to_sale=True).order_by('-updated_at').prefetch_related( 'items__variations')[:12]
    offerd_products = Product.objects.filter(brand=brand, offer=True, ready_to_sale=True).prefetch_related('items__variations')[:12]

    # تطبيق Paginator على جميع منتجات العلامة التجارية
    all_brand_products_list = Product.objects.filter(brand=brand, ready_to_sale=True).prefetch_related('items__variations')
    
    if all_brand_products_list.exists():
        paginator_all = Paginator(all_brand_products_list, 20) 

        page_all = request.GET.get('page_all', 1)
        try:
            all_brand_products = paginator_all.page(page_all)
        except (PageNotAnInteger, ValueError):
            all_brand_products = paginator_all.page(1)
        except EmptyPage:
            all_brand_products = paginator_all.page(paginator_all.num_pages)
        except Exception as e:
            logger.error(f"خطأ بدالة البراند داخل المتجر: {e}", exc_info=True)
            all_brand_products = paginator_all.page(1)  # توفير قيمة افتراضية عند أي خطأ غير متوقع
    else:
        all_brand_products = []    
    # ===========================================================
    query = request.GET.get('q', '')
    price_min = request.GET.get('price_min')
    price_max = request.GET.get('price_max')
    category_id = request.GET.get('category')
    available_only = request.GET.get('available_only')
   
    filters = Q(ready_to_sale=True) & Q(brand=brand)
    
    if query:
        filters &= (Q(name__icontains=query) | Q(tag__name__icontains=query))

    if price_min and price_min.isdigit():
        price_min = int(price_min)
        filters &= Q(
            Q(new_price__gte=price_min) | 
            (Q(offer=False) & Q(price__gte=price_min))
        )
        
    if price_max and price_max.isdigit():
        price_max = int(price_max)
        filters &= Q(
            Q(new_price__lte=price_max) | 
            (Q(offer=False) & Q(price__lte=price_max))
        )
    
    if category_id:
        # جلب التصنيف الأب
        parent_category = get_object_or_404(Category, id=category_id)
        # جلب التصنيفات الفرعية
        all_children_ids = parent_category.get_all_children_ids()
        # إضافة التصنيف الأساسي نفسه
        all_category_ids = [parent_category.id] + all_children_ids
        filters &= Q(category_id__in=all_category_ids)

    if available_only == "on" :
        filters &= Q(available=True)


    # جلب المنتجات بناءً على الفلاتر
    results = Product.objects.filter(filters,  ready_to_sale=True).prefetch_related('items__variations').distinct()
    
    # إعداد التصفح المرقم
    if results.exists():
        paginator = Paginator(results, 20)  # عرض 20 منتجًا في كل صفحة
        page = request.GET.get('page', 1)
        try:
            products = paginator.page(page)
        except (PageNotAnInteger, ValueError):
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)
        except Exception as e:
            logger.error(f"خطأ بدالة البراند داخل المتجر: {e}", exc_info=True)
            products = paginator.page(1)        
    else:
        products = []

    # البيانات الإضافية للعرض
    
    categories = cache.get('categories')
    if not categories:
        categories = Category.objects.filter(status='visible')
        cache.set('categories', categories, 60*15)
   
    products_count = results.count()
    
    
    context = {
        'brand': brand,
        'all_brand_products': all_brand_products, # جميع منتجات البراند
        'products': products, # المنتجات المفلترة
        'last_products': last_products,
        'offerd_products':offerd_products,
        'categories': categories, # قائمة التصنيفات التي داخل مربع الفلترة
        'products_count': products_count,
    }
    
    return render(request, 'store/brand.html', context)
# جميع البراندات
def all_brands(request):
    brands = Brand.objects.annotate(products_count=Count('products')).filter(products_count__gt=0).order_by('-products_count')
    brands_count = brands.count() if brands else 0
    context = {
        'brands': brands,
        'brands_count': brands_count,
    }
    return render(request, 'store/all_brands.html', context)
# ===================================================
# صفحة التصنيف
def category_page(request, slug):
    
    category = get_object_or_404(Category, slug=slug, status='visible')
    subcategories = Category.objects.filter(parent_category=category, status='visible') # استرجاع التصنيفات الفرعية التي تنتمي للتصنيف الأب
    
    all_categories = [category.id] + category.get_all_children_ids()
    all_category_products_list = Product.objects.filter(category_id__in=all_categories, ready_to_sale=True).prefetch_related('items__variations').distinct()
    
    total_products_count = all_category_products_list.count()# حساب العدد الكلي للمنتجات
    paginator = Paginator(all_category_products_list, 20)  # عرض 20 منتجًا في كل صفحة
    page = request.GET.get('page', 1)

    try:
        all_category_products = paginator.page(page)
    except (PageNotAnInteger, ValueError):
        all_category_products = paginator.page(1)
    except EmptyPage:
        all_category_products = paginator.page(paginator.num_pages)
    except Exception as e:
        logger.error(f"خطأ بدالة التصنيف داخل المتجر: {e}", exc_info=True)
        all_category_products = paginator.page(1)
    # ===========================================================
    # إضافة فلترة أخرى بناءً على معايير المستخدم (البحث، السعر، العلامة التجارية)
    query = request.GET.get('q', '')
    price_min = request.GET.get('price_min')
    price_max = request.GET.get('price_max')
    brand_id = request.GET.get('brand')
    available_only = request.GET.get('available_only')

    # فلترة المنتجات حسب التصنيف الأب والتصنيفات الفرعية
    filters = Q(ready_to_sale=True) & Q(category__in=all_categories)
    if query:
        filters &= (Q(name__icontains=query) | Q(tag__name__icontains=query) | Q(description__icontains=query) )
    if price_min and price_min.isdigit():
        price_min = int(price_min)
        filters &= Q(
            Q(new_price__gte=price_min) | 
            (Q(offer=False) & Q(price__gte=price_min))
        )
    if price_max and price_max.isdigit():
        price_max = int(price_max)
        filters &= Q(
            Q(new_price__lte=price_max) | 
            (Q(offer=False) & Q(price__lte=price_max))
        )
    if brand_id:

templates/store/ads-details.html
{% extends "partials/base.html" %}
{% load static %}      
{% block additional_css %}
    <link rel="stylesheet" href="{% static "/css/main-pages.css" %}">   
{% endblock %}
{% block content %}
        <!-- Start Searched-products  -->
        <div class="search ads-page" style="padding-top:100px">
            <div class="ads-details">
                <h1 class="ad-title"> {{ad.title}} </h1>
                <p class="ad-description"> {{ ad.info }}</p>
            </div>
            <hr class="sep">
            <div class="searched-products">
                <div class="container">
                    <div class="products-cards">
                        {% if ad_content %}
                            {% for ad_product in ad_content %}
                                {% for product in ad_product.product.all %}
                                    <!-- product-start -->
                                    <div class="specific">
                                        {% include "common/product-card.html" %}
                                    </div>
                                    <!-- product-end -->
                                {% endfor %}
                            {% endfor %}
                        {% else %}
                            {% include "common/no-result.html" %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <!-- End Searched-products  -->
{% endblock content %}

templates/store/all_brands.html
{% extends "partials/base.html" %}
{% load static %}

{% block additional_css %}
    <link rel="stylesheet" href="{% static "/css/main-pages.css" %}">   
{% endblock %}

{% block content %}
    <div class="search-page brand-bage" style='padding-top:100px;padding-bottom:30px;'>
        <div class="search">
            {% if  brands %}
                <div class="search-title">
                    <h2 style='color:var(--main-color);' >جميع البراندات<span style='color:var(--main-text-color);' >({{ brands_count }})</span></h2>
                    <div class="title-image"></div>
                </div>
                {% for brand in brands %}
                    <a href="{% url "store:brand" brand.title %}" aria-label="استعرض {{ brand.title}}" class="search-title">
                        <div class="title-image">
                            <img src="{{ brand.img.url }}" alt="{{ brand.title }}">
                        </div>
                        <h2>{{ brand.title }}<span>({{ brand.products_count }})</span></h2>
                    </a>
                {% endfor %}
            {% else %}
                <div class="searched-products">
                    <div class="container">
                        <div class="products-cards">
                            {% include "common/no-result.html" %}
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
        
    </div>
{% endblock content %}

{% block additional_js %}
    <script src=" {% static "/javascript/main-pages.js" %}" defer></script>
{% endblock %}

templates/store/copon-details.html
{% extends "partials/base.html" %}
{% load static %}

{% block content %}

<div class="cards-details">
    <div class="fav-page page">
        <div class="container">

        <a href="javascript:void(0);" onclick="goBack()">
            <span class="exit-button"><i class="fa-solid fa-arrow-left"></i></span>
        </a>

        <div class="upper-part">
            <div class="card-image">
                <img src="{{ copon.img.url }}" alt="Product Image">
            </div>
            <div class="name-price">
                <h3> {{ copon.name }}</h3>                   
                <div class="description">
                    <div><p>قيمة الخصم </p><span> {{ copon.value }} %</span></div>
                    <div><p> اقل قيمة للشراء </p><span>{{copon.min_bill_price}} دينار</span></div>

                </div>
                {% if copon.price != 0 %}
                    <p class="p-price"> {{ copon.price }} <i class="fa-solid fa-gem"></i></p>
                {% else %}
                    <p class="p-price free">مجاناً</p>
                {% endif %}
            </div>
        </div>

        <div class="lower-part">        
            <h3>شراء</h3>
            <div class="recipet">
              
                <div class="price">
                    {% if copon.price != 0 %}
                        <p>السعر {{ copon.price }} <i class="fa-solid fa-gem"></i></p>     
                    {% else %}
                        <p class="p-price ">السعر: <strong class='free'>مجاني</strong></p>
                    {% endif %}
                    {% if user.is_authenticated %}
                        {% if  user_points >= copon.price %}

                            <a href="{% url "store:buy-copon" copon.id %}" class="copon-buy-done-link">
                                إتمام عملية الشراء
                            </a>     

                        {% else %}
                            <span>نقاطك غير كافية!</span>
                        {% endif %}
                    {% else %}
                        <a href="{% url "accounts:sign" %}">سجل الدخول للشراء</a>
                    {% endif %} 
                </div>

                <a class="note" href="#">
                    هل ترغب بالحصول على البطاقة وليس لديك نقاط كافية؟ 
                </a>
                
            </div> 
        </div>
        </div>

    </div>
</div>


{% endblock content %}

templates/store/favourite.html
{% extends "partials/base.html" %}
{% load static %}
{% block additional_css %}
    <link rel="stylesheet" href="{% static "/css/main-pages.css" %}">   
{% endblock %}
{% block content %}
    <div class="fav-page page">
        <!-- Start Search Bar -->
        <div class="fav-search">
            <div class="search-bar">
                <div class="container">
                    <form id="filter-form" method="get" class="search" action="{% url 'store:favourite_page' %}">
                        {% if products %}
                            {% if request.GET.q  %}
                                <button class='clear-search' OnClick="resetFilters();"><i class="fa-solid fa-xmark"></i><p>إلغاء </p></button>
                            {% endif %}
                            <input type="search" class="search-input" id="search-query" name="q" placeholder="ما الذي تبحث عنه؟" value="{{ request.GET.q }}">                   
                            
                            <button id="clear-favourites-btn" type="button" class="empty"  title="إفراغ المفضلة">
                                <span class="delete">إفراغ</span>
                                <span class="items-count">({{ products_count }})</span>
                                <i class="fa-regular fa-trash-can"></i>
                            </button>
                             
                            <script>
                                const clearFavouritesUrl = "{% url 'store:clear_favourites' %}";
                                const csrfToken = "{{ csrf_token }}";
                            </script>
                                
                                
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
        <!-- End Search Bar -->
        <!-- Start fav-products  -->
        <div class="favorite">
            <div class="searched-products">
                <div class="container">
                    <div class="products-cards">
                        {% if request.GET.q %}
                            {% if search_results %}
                                {% for product in search_results %}
                                <!-- product-start -->
                                <div class="specific">
                                    {% include "common/product-card.html" %}
                                </div>
                                <!-- product-end -->
                                {% endfor %}  
                            {% else %}
                                {% include "common/no-result.html" %}
                            {% endif %}

                        {% else %}
                            {% if products %}        
                                {% for product in products %}
                                    <!-- product-start -->
                                    <div class="specific">
                                        {% include "common/product-card.html" %}
                                    </div>
                                    <!-- product-end -->
                                {% endfor %}
                            {% else %}
                                {% include "common/no-result.html" %}
                            {% endif %}
                        {% endif %}          
                    </div>
                </div>
            </div>
        </div>
        <!-- End fav-products  -->
    </div>

{% endblock content %}

{% block additional_js %}
    <script src=" {% static "/javascript/main-pages.js" %}" defer></script>
{% endblock %}

templates/store/index.html
{% extends "partials/base.html" %}
{% load static %}

{% block additional_css %}
    <link rel="stylesheet" href="{% static "/css/home.css" %}">  
    {% if ads %}{% for ad in ads %}<link rel="preload" href="{{ ad.img.url }}" as="image" fetchpriority="high">{% endfor %}{% endif %}
{% endblock %}

{% block content %}
    <div class="home-page">
        <!-- Start Ads -->
        <div class="ads">
            <div class="welcome">
                <h2>اهلا بك {% if user_name %}{{ user_name  }}{% endif %}</h2>
                <p> لدينا عروض جديدة  من اجلك! </p>
            </div>
            <section  id="tranding">
                    <div class="swiper tranding-slider">
                        <div class="swiper-wrapper">
                            {% if ads %} 
                                {% for ad in ads %}
                                    <!-- Slide-start -->
                                    <div class="swiper-slide tranding-slide">
                                        <div class="tranding-slide-img">
                                            <a href="{{ ad.get_ad_url }}" aria-label="استعرض {{ad.title}}">
                                                <img class='swiper-lazy'
                                                    src="{% static 'images/rectangle-default.webp' %}"                                                     
                                                    data-src="{{ ad.img.url }}" 
                                                    alt="{{ ad.title }}" 
                                                    width="1600" height="900" 
                                                >
                                            </a>
                                        </div>
                                    </div>
                                    <!-- Slide-end -->
                                {% endfor %}
                            {% else %}
                                <h2> نعتذر لايوجد اعلانات لعرضها حاليا </h2>
                            {% endif %}
                        </div>
                    </div>     
            </section>
        </div>
        <!-- End Ads -->
        <!-- Start Brands -->
        <div class="brands">
            <h3>
                تسوق من افضل البراندات      
            </h3>
            <hr class="upper-sep">
            <section  id="branding">
                <div class="swiper branding-slider">
                    <div class="swiper-wrapper">
                        {% if brands %} 
                            {% for brand in brands %}
                                <!-- brand-logo-start -->
                                <div class="swiper-slide branding-slide">
                                    <div class="branding-slide-img">
                                        <a href="{% url "store:brand" brand.title %}" aria-label="استعرض {{ brand.title}}">
                                            <img class=''
                                                src="{{ brand.img.url }}" 
                                                alt="{{ brand.title }}" 
                                                width="80" height="80"
                                            >
                                        </a>
                                    </div>
                                </div>
                                <!-- brand-logo-end -->
                            {% endfor %}
                        {% else %}
                            <h4 > لايوجد ماركات لعرضها حاليا </h4>
                        {% endif %}
                    </div>
                </div>     
            </section>
        </div>
        <!-- End Brands -->
        <!-- Start Offer Products Section -->
        <hr class="sep">
        <section  id="products">
                <a href="{% url "store:offer_page" %}" aria-label="استعرض اقوى العروض">
                    <div class="title">
                        <h2> اقوى العروض</h2>
                        <i class="fa-solid fa-angles-left"></i>
                    </div>
                </a>  
                <div class="swiper products-slider">
                    <div class="swiper-wrapper">
                        {% for product in offered_products %}
                            {% include "common/product-card.html" %}
                        {% endfor %}
                    </div>
                </div> 
        </section>
        <!-- End Offer Products Section -->
        <!-- Start Best sales Products Section -->
        {% if best_sales_products %}
            <hr class="sep">
            <section  id="products">
                <a href="{% url "store:best-sales" %}" aria-label="استعرض المنتجات الأعلى مبيعاً">
                    <div class="title">
                        <h2>المنتجات الأعلى مبيعاً</h2>
                        <i class="fa-solid fa-angles-left"></i>
                        </div>
                    </a>  
                    <div class="swiper products-slider">
                        <div class="swiper-wrapper">
                            {% for product in best_sales_products %}
                                {% include "common/product-card.html" %}
                            {% endfor %}
                        </div>
                    </div> 
                </section>
        {% endif %}
        <!-- End Best sales Products Section -->
        {% for category in categories %}
        <!-- Start Products Section -->
            <hr class="sep">
            <section  id="products">
                    <a href="{% url "store:category" category.slug %}" aria-label="استعرض {{category.name}}">
                        <div class="title">
                            <h2> {{ category.name }} </h2>
                            <i class="fa-solid fa-angles-left"></i>
                        </div>
                    </a>  
                    <div class="swiper products-slider">
                        <div class="swiper-wrapper">
                            {% for product in category.products.all %}
                                {% if product.featured and product.ready_to_sale %} 
                                    {% include "common/product-card.html" %}
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div> 
            </section>
            <!-- End Products Section -->
        {% endfor %}
    </div>

{% endblock content %}

{% block additional_js %}
    <script src=" {% static "/javascript/home.js" %}" ></script>
{% endblock %}

templates/store/offline.html
{% load static %}
<!DOCTYPE html>
<html lang="ar">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static "/css/normalize.css" %}">  
    <link rel="stylesheet" href="{% static "/css/all.css" %}"> 
    <link rel="stylesheet" href="{% static "/css/all.min.css" %}">     
    <link rel="stylesheet" href="{% static "/css/offline-style.css" %}"> 
    <title>غير متصل</title>
</head>
<body>
    <div>
        <h1> يرجى التحقق من اتصالك بالإنترنت</h1>
        <span>
            <i class="fa-solid fa-wifi"></i>
            <i class="fa-solid fa-slash"></i>
        </span>
    </div>
</body>
</html>